Repository mario-r99/jarvil, pull requests merged in 2021-06, with the labels that each got.

#58 Fix/rename brightness to climate service
  docker/pc-1/docker-compose.yml
  docker/pi-3/docker-compose.yml
  services/brightness-service-pc/requirements.txt
  services/climate-service-pc/climate-service.py
  services/climate-service-pc/requirements.txt
  services/climate-service-pi/Dockerfile
  services/climate-service-pi/climate-service.py
  services/climate-service-pi/requirements.txt
  services/mqtt-client/client.py
Labels: invalid

#74 MQTT-client: Fixed service name identification
  services/mqtt-client/client.py
Labels: bug

#81 Mqtt client setpoint logging
  services/mqtt-client/client.py
Labels: enhancement
